name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Copy .env
        run: |
          cp .env.example .env

      - name: Run composer install
        run: |
          composer install --no-interaction --no-suggest

      - name: Run tests
        run: |
          php artisan test
